services:
  - type: web
    name: my-application
    runtime: docker
    region: oregon
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: SESSION
        value: "RGNK~SpCmaWzE"
      - key: DATABASE_URL
        fromDatabase:
          name: postgresql://yagami_light_user:ZwfM4340Tf9EDpSQZXn9GSr4zXu9Ymhb@dpg-d645lpvfte5s73fv5ddg-a.frankfurt-postgres.render.com/yagami_light
          property: connectionString
