services:
  - type: web
    name: Ghali
    runtime: docker
    region: Frankfurt 
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: SESSION
        value: "RGNK~SpCmaWzE"
      - key: DATABASE_URL
        fromDatabase:
          name: Yagami Light 
          property: connectionString
